<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PS-L6" failures="1" tests="1" name="com.report.test.transactionLog" time="29.332" errors="0" timestamp="2025-07-18T15:10:33 IST" skipped="0">
  <testcase classname="com.report.test.transactionLog" name="verify_purchaseIDJson" time="29.332">
    <failure message="expected [686cf3b48c6ad27c9c7e3a9d] but found [Not found]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [686cf3b48c6ad27c9c7e3a9d] but found [Not found]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.paysecure_Report.pages.transaction_Log_page.verifyPurchaseID(transaction_Log_page.java:152)
at com.report.test.transactionLog.verify_purchaseIDJson(transactionLog.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Click on the Date range
select date range :- Last 30 Days
User enter purchase ID in Purchase ID text Field
Click on Search Button]]>
    </system-out>
  </testcase> <!-- verify_purchaseIDJson -->
  <system-out>
    <![CDATA[User enter ID in Username field
User Enter Password in password field
Click on submit button in login page
Click on Report Module
Click on Transaction Log Sub Module
Verify user is on the Transaction Log page
Click on the Date range
select date range :- Last 30 Days
User enter purchase ID in Purchase ID text Field
Click on Search Button]]>
  </system-out>
</testsuite> <!-- com.report.test.transactionLog -->
